on: [pull_request]
name: Continuous Integration

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python # Set Python version
      uses: actions/setup-python@v2
    - name: Install Pytest
      run: |
        python -m pip install pytest --upgrade pip
    - name: Test with pytest
      run: pytest tests.py       